### PR TITLE
Allow redhat like systems (#14)

### PR DESCRIPTION
**Pull request by bnoahpro**

### CODE REVIEW

**Comment by tersmitten** [comment]
I prefer not making the role more "complex" to support other non-supported distributions

**Comment by EliasBoulharts** [comment]
I do not agree with you, it is no more complexe, the "package" module does everything for all distributions. This is an Ansible module, which guarantees trouble-free functioning over time.

**Comment by tersmitten** [comment]
But `cache_valid_time` is gone now and that's required for the role to work properly

**Comment by EliasBoulharts** [comment]
This is not necessary for the role, it is a feature to use the cache with apt. As we are using package only once, I don't know why valid cache time is required.

**Comment by tersmitten** [comment]
Because an out-of-date cache will make `apt` unhappy. That's why it is in all our roles.

**Pull request closed without merging**
