### PR TITLE
Add dnsmasq_etc_default_options var

### PR DESCRIPTION
**Pull request by vicyap**
Addresses issue #5

* Adds `dnsmasq_etc_default_options` which appends lines to
/etc/default/dnsmasq

### CODE REVIEW

**Comment by tersmitten** [comment]
I think I prefer something like `dnsmasq_dnsmasq_conf`. This way we can support any option in `/etc/default/dnsmasq`. What do you think?

**Comment by vicyap** [comment]
Hello, thanks for replying and sorry for my late reply, I was busy last week.

`dnsmasq_dnsmasq_conf` is already being used for `/etc/dnsmasq.conf`, so that name won't work.

I'm open to renaming `dnsmasq_etc_default_options` to something else.

**Comment by vicyap** [comment]
Hi, what is left to get this merged? I currently have a workaround for this missing feature and would prefer to use what's in this PR. Thank you.

**Comment by tersmitten** [comment]
I'll try to have a look soon

**Pull request closed without merging**
